/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itgo.teachjava2;

import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author tomnyson
 */
public class frmFlaskScreen extends javax.swing.JFrame {

    /**
     * Creates new form frmFlaskScreen
     */
    pThread t1;
    timeThread t2;
    public frmFlaskScreen() {
        initComponents();
        t1 = new pThread((process));
        t1.start();
        t2 = new timeThread(lbTime);
        t2.start();

    }

    class pThread extends Thread {

        JProgressBar pbar;

        pThread(JProgressBar bar) {
            pbar = bar;
        }

        public void run() {

            int min = 0;
            int max = 100;
            process.setMinimum(min);
            process.setMaximum(max);
            process.setValue(0);
            process.setStringPainted(true);
            for (int i = 0; i < 100; i++) {
                if (i > 30 && i < 70) {
                    process.setString("wait for sometime");
                } else if (i > 70) {
                    process.setString("almost finished loading");
                } else {
                    process.setString("loading started");
                }
                process.setValue(i + 10);
                try {
                    sleep(3000);
                    i += 20;

                } catch (InterruptedException ex) {
                    Logger.getLogger(frmFlaskScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }

    class timeThread extends Thread {
        JLabel lb;
        
        timeThread(JLabel lable) {
            lb = lable;
        }

        @Override
        public void run() {
            try {
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                while(true) {
                sleep(1000);
                Date date = new Date();
                System.out.println(formatter.format(date));
                lb.setText(formatter.format(date));
                }
                
            } catch (InterruptedException ex) {
                Logger.getLogger(frmFlaskScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        process = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOADING...");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 190, -1));

        lbTime.setText("time");
        jPanel2.add(lbTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/tomnyson/NetBeansProjects/teachjava2/src/main/java/com/itgo/teachjava2/icon/hinh-nen-background-dep-1.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        process.setOpaque(true);
        getContentPane().add(process, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 380, 550, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFlaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFlaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFlaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFlaskScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFlaskScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTime;
    private javax.swing.JProgressBar process;
    // End of variables declaration//GEN-END:variables
}
